### ISSUE TITLE
数据血缘问题

### ISSUE THREAD

**Issue by lx096** [anlasite/durineage#2]
你好！最近我正在做对字段级别的数据血缘探索，在github看了你的代码，写的很好，我想问一下，你后面对这个代码还有优化吗？比如：”所有字段格式：别名.字段名“这个有办法解决吗？

**Comment by anlasite** [comment]
很抱歉这么久才回复你，因为无人问津，所以这代码早就放弃维护了。还有一个原因，就是当初写这代码太费脑了。
阁下实在太过谦了，我自己水平我自己知道，代码没法用“好”来形容。
我会尽量尝试重新维护这个代码，但是因为代码太烧脑，阁下还是尽量靠自己吧。
